#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence


ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = ROOT / "svg_to_paint_by_numbers_pdf.py"
MAP_PATH = ROOT / ".opencode" / "python-map.md"
BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED: python-map -->"
END_MARKER = "<!-- END AUTOGENERATED: python-map -->"


@dataclass
class MethodInfo:
    name: str
    signature: str
    lineno: int
    end_lineno: int


@dataclass
class ClassInfo:
    name: str
    lineno: int
    end_lineno: int
    doc: str
    decorators: List[str]
    fields: List[str]
    methods: List[MethodInfo]


@dataclass
class FunctionInfo:
    name: str
    signature: str
    lineno: int
    end_lineno: int
    doc: str


def shorten_docstring(node: ast.AST) -> str:
    doc = ast.get_docstring(node) or ""
    first_line = doc.strip().splitlines()[0].strip() if doc.strip() else ""
    return first_line or "-"


def unparse(node: ast.AST | None) -> str:
    if node is None:
        return ""
    return ast.unparse(node)


def format_arg(arg: ast.arg, default: ast.AST | None) -> str:
    text = arg.arg
    if arg.annotation is not None:
        text += f": {unparse(arg.annotation)}"
    if default is not None:
        text += f" = {unparse(default)}"
    return text


def format_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = node.args
    parts: List[str] = []

    positional = list(args.posonlyargs) + list(args.args)
    positional_defaults: List[ast.AST | None] = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)

    for index, arg in enumerate(args.posonlyargs):
        parts.append(format_arg(arg, positional_defaults[index]))
    if args.posonlyargs:
        parts.append("/")

    offset = len(args.posonlyargs)
    for index, arg in enumerate(args.args):
        parts.append(format_arg(arg, positional_defaults[offset + index]))

    if args.vararg is not None:
        vararg = f"*{args.vararg.arg}"
        if args.vararg.annotation is not None:
            vararg += f": {unparse(args.vararg.annotation)}"
        parts.append(vararg)
    elif args.kwonlyargs:
        parts.append("*")

    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(format_arg(arg, default))

    if args.kwarg is not None:
        kwarg = f"**{args.kwarg.arg}"
        if args.kwarg.annotation is not None:
            kwarg += f": {unparse(args.kwarg.annotation)}"
        parts.append(kwarg)

    signature = f"({', '.join(parts)})"
    if node.returns is not None:
        signature += f" -> {unparse(node.returns)}"
    return signature


def decorator_names(node: ast.ClassDef) -> List[str]:
    names: List[str] = []
    for decorator in node.decorator_list:
        names.append(unparse(decorator))
    return names


def class_fields(node: ast.ClassDef) -> List[str]:
    fields: List[str] = []
    for child in node.body:
        if isinstance(child, ast.AnnAssign) and isinstance(child.target, ast.Name):
            fields.append(child.target.id)
        elif isinstance(child, ast.Assign):
            for target in child.targets:
                if isinstance(target, ast.Name):
                    fields.append(target.id)
    return fields


def class_methods(node: ast.ClassDef) -> List[MethodInfo]:
    methods: List[MethodInfo] = []
    for child in node.body:
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            methods.append(
                MethodInfo(
                    name=child.name,
                    signature=f"{child.name}{format_signature(child)}",
                    lineno=child.lineno,
                    end_lineno=getattr(child, "end_lineno", child.lineno),
                )
            )
    return methods


def parse_source(source_path: Path) -> tuple[List[ClassInfo], List[FunctionInfo]]:
    module = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
    classes: List[ClassInfo] = []
    functions: List[FunctionInfo] = []

    for node in module.body:
        if isinstance(node, ast.ClassDef):
            classes.append(
                ClassInfo(
                    name=node.name,
                    lineno=node.lineno,
                    end_lineno=getattr(node, "end_lineno", node.lineno),
                    doc=shorten_docstring(node),
                    decorators=decorator_names(node),
                    fields=class_fields(node),
                    methods=class_methods(node),
                )
            )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(
                FunctionInfo(
                    name=node.name,
                    signature=f"{node.name}{format_signature(node)}",
                    lineno=node.lineno,
                    end_lineno=getattr(node, "end_lineno", node.lineno),
                    doc=shorten_docstring(node),
                )
            )

    return classes, functions


def render_class_lines(classes: Sequence[ClassInfo]) -> List[str]:
    lines: List[str] = []
    lines.append("### Classes")
    if not classes:
        lines.append("- None found")
        return lines

    for info in classes:
        line_ref = f"svg_to_paint_by_numbers_pdf.py:{info.lineno}"
        decorators = f" | decorators: {', '.join(info.decorators)}" if info.decorators else ""
        lines.append(f"- `{info.name}` (`{line_ref}`){decorators}")
        lines.append(f"  - doc: {info.doc}")
        if info.fields:
            lines.append(f"  - fields: {', '.join(f'`{field}`' for field in info.fields)}")
        if info.methods:
            preview = ", ".join(f"`{method.name}()`" for method in info.methods[:6])
            if len(info.methods) > 6:
                preview += ", ..."
            lines.append(f"  - methods: {preview}")
    return lines


def render_function_lines(functions: Sequence[FunctionInfo]) -> List[str]:
    lines: List[str] = []
    lines.append("### Functions")
    if not functions:
        lines.append("- None found")
        return lines

    for info in functions:
        line_ref = f"svg_to_paint_by_numbers_pdf.py:{info.lineno}"
        lines.append(f"- `{info.signature}` (`{line_ref}`)")
        lines.append(f"  - doc: {info.doc}")
    return lines


def build_generated_block(classes: Sequence[ClassInfo], functions: Sequence[FunctionInfo]) -> str:
    lines: List[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("_Generated from `svg_to_paint_by_numbers_pdf.py` by `scripts/generate_python_map.py`. Do not edit this block by hand._")
    lines.append("")
    lines.append(f"- Top-level classes: `{len(classes)}`")
    lines.append(f"- Top-level functions: `{len(functions)}`")
    lines.append("")
    lines.extend(render_class_lines(classes))
    lines.append("")
    lines.extend(render_function_lines(functions))
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_block(content: str, generated_block: str) -> str:
    start = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(f"Missing markers in {MAP_PATH}")
    end += len(END_MARKER)
    return content[:start] + generated_block + content[end:]


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Refresh the autogenerated AST inventory in .opencode/python-map.md")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Exit non-zero if the generated block is stale")
    mode.add_argument("--write", action="store_true", help="Write the refreshed block back to the markdown file")
    args = parser.parse_args(list(argv) if argv is not None else None)

    classes, functions = parse_source(SOURCE_PATH)
    generated_block = build_generated_block(classes, functions)
    current = MAP_PATH.read_text(encoding="utf-8")
    updated = replace_block(current, generated_block)

    if args.check:
        if current != updated:
            print(f"Stale generated block in {MAP_PATH}")
            return 1
        print(f"Generated block is up to date in {MAP_PATH}")
        return 0

    if args.write or not args.check:
        MAP_PATH.write_text(updated, encoding="utf-8")
        print(f"Updated {MAP_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
